version: '3'
services:
  db:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: db1234
    volumes:
      - dbpostgres:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "3000:3000"
      - "1234:1234"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
volumes:
    dbpostgres: